async (page) => {
  const MAPS = {"collection": ["collections/mong-doi-thuong", "collection.html?handle=mong-doi-thuong", [[".collection_title", ".collection__title"], [".content-product-list", ".product-grid"], [".content-product-list .pro-loop", ".product-grid .pro-loop"], [".content-product-list .pro-loop:nth-child(5)", ".product-grid .pro-loop:nth-child(5)"], [".content-product-list .imageno1", ".product-grid .img-1"], [".content-product-list .pro-loop-name", ".product-grid .pro-loop__name"], [".content-product-list .pro-loop-price strong", ".product-grid .pro-loop__price strong"], ["#footer", ".footer"]]], "product": ["products/dung-dress", "product.html?handle=dung-dress", [[".productWrapLeft", ".product__gallery"], [".productWrapLeft .mobile-flex-slider > div:first-child img, .mobile-flex-slider .slick-active img", ".product__images img"], [".productWrapRight", ".product__side"], [".backproduct", ".product__back"], [".productTitle", ".product__title"], [".productSku", ".product__sku"], [".productPriceMain", ".product__price-main"], [".product-sw-line:nth-child(1)", ".sw-line--color"], [".product-sw-line:nth-child(2)", ".sw-line--size"], [".sw-color-nauvan-label", ".sw-item--color"], [".product-sw-line:nth-child(2) .product-sw-select-item", ".sw-item--size"], [".flexaction", ".product__links"], [".itemQuantity", ".product__qty"], ["#addToCart", ".btn-add"], [".productRelate .section-title-all h2", ".product__related .section-head h2"], [".productRelate .pro-loop", ".product__related .pro-loop"]]], "search": ["search?q=dam&type=product", "search.html?q=dam", [[".breadcrumb-shop", ".breadcrumb"], [".searchPageWrap", ".search-page__wrap"], [".searchPageHeader h1", ".search-page__head h1"], [".subtxt", ".js-search-count"], [".searchResult", ".js-search-for"], [".search_box", ".search-page__form input"], [".searchResultList", ".js-search-grid"], [".searchResultList .pro-loop", ".js-search-grid .pro-loop"], ["#pagination", ".js-search-pages"]]], "page": ["pages/chinh-sach-doi-hang", "page.html?handle=chinh-sach-doi-hang", [[".page-layout", ".page-layout"], [".page-wrapper", ".page-wrapper"], [".heading-page h1", ".page-wrapper h1"], [".content-page p", ".page-content p"]]], "contact": ["pages/lien-he", "contact.html", [[".box_contact > div:first-child", ".contact__info"], [".titlecontact", ".contact__title"], [".box_contact > div:nth-child(2)", ".contact__form-col"], ["#namecuaban", ".contact__form input"], ["textarea#messagecuaban", ".contact__form textarea"], [".guithongtin a", ".contact__send button"], [".page-about-new-contact-map iframe", ".contact__map iframe"], [".box_contact2 img", ".contact__image img"]]], "cart": ["cart", "cart.html", [["#cart-page h1, #cart-page h3, #cart-page .title-page", ".cart-page__empty h3"]]], "blog": ["blogs/news", "blog.html", [["#blog h1, #blog h2:first-child", ".blog__title"], ["#blog img", ".blog__item img"], ["#blog .article-title, #blog h2 a, #blog h3", ".blog__item h2"]]]};
  const o = await page.context().newPage();
  const collect=(p,sels)=>p.evaluate((sels)=>sels.map(s=>{const e=document.querySelector(s); if(!e) return null; const r=e.getBoundingClientRect(); const cs=getComputedStyle(e); return {r:[r.x,r.y+scrollY,r.width,r.height].map(Math.round), vis: cs.display!=='none'&&r.width>0, st:[cs.fontSize,cs.fontWeight,cs.lineHeight,cs.color,cs.textTransform].join('|')};}),sels);
  const out={};
  for (const [w,h] of [[1440,900],[390,844]]) {
    await o.setViewportSize({width:w,height:h}); await page.setViewportSize({width:w,height:h});
    for (const [k,[ou,cu,map]] of Object.entries(MAPS)) {
      await o.goto('https://mauvevn.com/'+ou,{waitUntil:'domcontentloaded'}); await page.goto('http://localhost:5500/'+cu);
      await o.waitForTimeout(1500); await page.waitForTimeout(800);
      const a=await collect(o,map.map(m=>m[0])); const b=await collect(page,map.map(m=>m[1]));
      const d=[]; map.forEach((m,i)=>{const A=a[i],B=b[i]; if(!A||!B){d.push(m[1]+' missing '+(A?'clone':'orig')); return;} if(A.vis!==B.vis){d.push(m[1]+' vis o='+A.vis+' c='+B.vis);return;} if(!A.vis) return; if(A.r.some((v,j)=>Math.abs(v-B.r[j])>2)) d.push(m[1]+' rect o='+A.r+' c='+B.r); if(A.st!==B.st) d.push(m[1]+' st o='+A.st+' c='+B.st);});
      out[k+'@'+w]=d;
    }
  }
  await o.close();
  return out;
}